version: '3'

volumes:
  tyr_data:
  tyr_instance_conf:
  pgdata_jormun:
  pgdata_cities:

services:
  instances_configurator:
    image: navitia/instances-configurator:${TAG}
    volumes:
      - tyr_data:/srv/ed
      - tyr_instance_conf:/etc/tyr.d
    environment:
      - INSTANCE_default=
    depends_on:
      - database
      - cities_database

  database:
    image: postgis/postgis:13-3.2
    environment:
      - POSTGRES_USER=navitia
      - POSTGRES_PASSWORD=navitia
      - POSTGRES_DB=jormungandr
    volumes:
      - pgdata_jormun:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management

  redis:
    image: redis:3-alpine

  kraken-default:
    image: navitia/kraken:${TAG}
    environment:
      - KRAKEN_GENERAL_instance_name=default
      - KRAKEN_GENERAL_database=/srv/ed/output/default.nav.lz4
      - KRAKEN_GENERAL_is_realtime_enabled=true
      - KRAKEN_GENERAL_is_realtime_add_enabled=true
      - KRAKEN_GENERAL_is_realtime_add_trip_enabled=true
      - KRAKEN_BROKER_host=rabbitmq
      - KRAKEN_BROKER_port=5672
      - KRAKEN_BROKER_username=guest
      - KRAKEN_BROKER_password=guest
      - KRAKEN_BROKER_exchange=navitia
      - KRAKEN_BROKER_rt_topics=realtime.default.test
    volumes:
      - tyr_data:/srv/ed:ro
    expose:
      - "30000"
    depends_on:
      - rabbitmq

  jormungandr:
    image: navitia/jormungandr:${TAG}
    environment:
      - JORMUNGANDR_SQLALCHEMY_DATABASE_URI=postgresql://navitia:navitia@database/jormungandr
      - JORMUNGANDR_INSTANCE_DEFAULT={"key":"default","zmq_socket":"tcp://kraken-default:30000"}
      - JORMUNGANDR_MEMORY_CACHE_CONFIGURATION={ "CACHE_TYPE":"uwsgi","CACHE_UWSGI_NAME":"jormungandr"}
      - APACHE_SERVER_NAME=localhost
      - APACHE_SERVER_ALIAS=127.0.0.1
    ports:
      - "80:80"
    depends_on:
      - database
      - redis


  tyr_worker:
    image: navitia/tyr-worker:${TAG}
    volumes:
      - tyr_data:/srv/ed
      - tyr_instance_conf:/etc/tyr.d
    environment:
      - TYR_CITIES_DATABASE_URI=postgresql://navitia:navitia@cities_database/cities
      - TYR_CITIES_OSM_FILE_PATH=/srv/ed/
      - TYR_CELERY_BROKER_URL=amqp://guest:guest@localhost:5672//
      - TYR_KRAKEN_BROKER_URL=amqp://guest:guest@localhost:5672//
    depends_on:
      - database
      - cities_database

  tyr_beat:
    image: navitia/tyr-beat:${TAG}
    volumes:
      - tyr_data:/srv/ed
      - tyr_instance_conf:/etc/tyr.d
    depends_on:
      - database
      - cities_database

  tyr_web:
    image: navitia/tyr-web:${TAG}
    volumes:
      - tyr_data:/srv/ed
      - tyr_instance_conf:/etc/tyr.d
    ports:
      - "9898:80"
    environment:
      - TYR_CITIES_DATABASE_URI=postgresql://navitia:navitia@cities_database/cities
      - TYR_CITIES_OSM_FILE_PATH=/srv/ed/
      - TYR_CELERY_BROKER_URL=amqp://guest:guest@localhost:5672//
      - TYR_KRAKEN_BROKER_URL=amqp://guest:guest@localhost:5672//
    depends_on:
      - database
      - cities_database

  cities_database:
    image: postgis/postgis:13-3.2
    environment:
      - POSTGRES_USER=navitia
      - POSTGRES_PASSWORD=navitia
      - POSTGRES_DB=cities
    volumes:
      - pgdata_cities:/var/lib/postgresql/data
