version: "3"

volumes:
  data:
    driver: local

services:
  asgard-data:
    image: docker-registry.canaltp.fr/navitia/asgard-data-downloader:master
    environment:
        - MINIO_KEY=${MINIO_KEY}
        - MINIO_SECRET=${MINIO_SECRET}
        - MINIO_HOST=${MINIO_HOST}
        - MINIO_BUCKET=${MINIO_BUCKET}
        - MINIO_COVERAGE=${MINIO_COVERAGE}
        - MINIO_VALHALLA_VERSION=${MINIO_VALHALLA_VERSION}
    volumes:
      - data:/data/valhalla

  asgard-valhalla-service:
    image: docker-registry.canaltp.fr/navitia/asgard-valhalla-service:${MINIO_VALHALLA_VERSION}
    depends_on:
      - "asgard-data"
    volumes:
      - data:/data/valhalla
    expose:
      - "8002"
    entrypoint: ["sh", "-c", "wait-for-data.sh && valhalla_service /data/valhalla/valhalla.json 1"]

  asgard:
    image: docker-registry.canaltp.fr/navitia/asgard-app:${ASGARD_APP_TAG}
    depends_on:
      - "asgard-data"
      - "asgard-valhalla-service"

    volumes:
      - data:/data/valhalla

    expose:
      - "6000"

    entrypoint: ["sh", "-c", "wait-for-data.sh && /usr/bin/asgard"]

    environment:
      - ASGARD_SOCKET_PATH=tcp://*:6000
      - ASGARD_WALKING_CACHE_SIZE=50000
      - ASGARD_BIKE_CACHE_SIZE=50000
      - ASGARD_CAR_CACHE_SIZE=50000
      - ASGARD_NB_THREADS=3
      - ASGARD_METRICS_BINDING=0.0.0.0:8080
      - ASGARD_VALHALLA_SERVICE_URL=asgard-valhalla-service:8002
      - ASGARD_VALHALLA_CONF=/data/valhalla/valhalla.json
