version: "3"


volumes:
  data:
    driver: local

services:
  asgard-valhalla-service:
    image: navitia/asgard-valhalla-service:${VALHALLA_VERSION}
    volumes:
      - data:/data/valhalla:ro
    entrypoint: ["sh", "-c", "wait-for-data.sh && valhalla_service /data/valhalla/valhalla.json 1"]
    expose:
      - "8002"

  asgard:
    image: navitia/asgard-app:${ASGARD_APP_TAG}
    depends_on:
      - "asgard-valhalla-service"
    restart: always
    volumes:
      - data:/data/valhalla:ro
    entrypoint: ["sh", "-c", "wait-for-data.sh && /usr/bin/asgard"]
    environment:
      - ASGARD_SOCKET_PATH=tcp://*:6000
      - ASGARD_WALKING_CACHE_SIZE=50000
      - ASGARD_BIKE_CACHE_SIZE=50000
      - ASGARD_CAR_CACHE_SIZE=50000
      - ASGARD_NB_THREADS=3
      - ASGARD_METRICS_BINDING=0.0.0.0:8080
      - ASGARD_VALHALLA_SERVICE_URL=asgard-valhalla-service:8002
      - ASGARD_VALHALLA_CONF=/data/valhalla/valhalla.json
    expose:
      - "6000"
