FROM navitia/master


# copy package from context inside the docker
COPY navitia-kraken_*.deb navitia-monitor-kraken_*.deb ./

# install navitia-kraken package
RUN dpkg -i ./navitia-kraken_*.deb 
RUN dpkg -i ./navitia-monitor-kraken_*.deb
RUN apt-get install -f -y

# put the binary in /srv/kraken
RUN mkdir -p /srv/kraken
RUN cp /usr/bin/kraken /srv/kraken/kraken

RUN pip install --no-cache-dir -r /usr/share/monitor_kraken/requirements.txt

COPY app.py /usr/lib/python2.7/dist-packages/monitor_kraken/.
COPY run_kraken.sh /usr/src/app/run_kraken.sh
RUN chmod +x /usr/src/app/run_kraken.sh

RUN ln -s /usr/lib/python*/dist-packages/monitor_kraken/app.py monitor_kraken

EXPOSE 30000

ENV KRAKEN_GENERAL_zmq_socket=tcp://*:30000
ENV KRAKEN_GENERAL_log_level=INFO
HEALTHCHECK CMD nc -z localhost 30000 || exit 1

ENV MONITOR_HOST=0.0.0.0

CMD ["bash", "/usr/src/app/run_kraken.sh"]
